[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000

import streamlit as st

# crear una casilla de verificaci칩n
build_histogram = st.checkbox('Construir un histograma')

if build_histogram: # si la casilla de verificaci칩n est치 seleccionada
    st.write('Construir un histograma para la columna od칩metro')
        ...